### PR TITLE
Added 64-bit build configuration

### PR DESCRIPTION
**Pull request by Jusonex**
Renamed project files
Increased warning level and adjusted some compiler/linker options
Updated 32-bit lua lib
Included bcrypt directly and removed lib dependency

### CODE REVIEW

**Comment by Jusonex** [comment]
64-Bit Build: https://jusonex.net/public/mta/ml_bcrypt.dll

**Comment by qaisjp** [comment]
It's not a huge issue but the filters file has localised names, please can you fix that?

**Comment by Jusonex** [comment]
Of course - done.

**Comment by qaisjp** [comment]
Builds fine for me, thanks for the pull request @Jusonex!

**Pull request merged**
